apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: segundo-pod #definido para a comunicaçao do svc-pod2  com este pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80