apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec: 
  type: NodePort #serve para expor o ip para fora do cluster
  ports:
    - port: 80
      #targetPort: 80 se não explicitar ele ja assume a mesma porta do port
      nodePort: 30000
  selector:
    app: primeiro-pod    
