apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticiais-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      env:
        - configMapKeyRef:
          name: db-configmap

       
             