apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
    #target port é definido igual 80
      NodePort: 30000
  selector:
    app: portal-noticias