apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
    #target port é definido igual 80
      NodePort: 30001
  selector:
    app: sistema-noticias